import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import SubscriptionProvider from './components/SubscriptionProvider';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Clinkz | Categorize, Track, Share Your Shopping ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={nunito.className}>
        <SubscriptionProvider>{children}</SubscriptionProvider>
      </body>
    </html>
  );
}
